### ISSUE TITLE
[BUG] Current NPC HP reset after next turn

### ISSUE THREAD

**Issue by DarKDinDoN** [kandashi/Next-Up#102]
Hello,

FVTT 0.8.6
Nextup: latest
Browser: Chrome
Dnd: 1.3.5

When I remove HP from a NPC token, and it is **that** NPC turn, when pressing the NEXT TURN button, the NPC goes back to its previous HP count.

https://user-images.githubusercontent.com/1687854/123014386-78e21580-d3c6-11eb-9117-3fc4ae7a13d3.mp4

**Comment by kandashi** [comment]
Is this will no other modules enabled ?

**Comment by DarKDinDoN** [comment]
@kandashi nope, only next up module.

**Comment by kandashi** [comment]
Can you check without any modules, I'm not sure how next up would be triggering this

**Comment by DarKDinDoN** [comment]
@kandashi made the test, no issue without any modules.
Note that the demo video showcases a combat without any PCs, only NPCs, could it be smt in relation with combats without PCs?

**Comment by DarKDinDoN** [comment]
@kandashi made the test with a PCs as well in the combat. Same issue.

**Comment by DarKDinDoN** [comment]
@kandashi tested in a new world with only next up & libwrapper (as suggested by the module).
No prob at first.
Then, after matching my world configuration, trouble started. Maybe if you match this exact same config, you will have the issue?
![image](https://user-images.githubusercontent.com/1687854/123235865-90132700-d4dc-11eb-9ca3-ae9c9e4fdb6e.png)

**Comment by kandashi** [comment]
Well, I can replicate, now to figure out whats up

**Comment by kandashi** [comment]
Found the problem, fix going live soon
