### ISSUE TITLE
[BUG] Sheet is stuck

### ISSUE THREAD

**Issue by DarKDinDoN** [kandashi/Next-Up#103]
Hello,

FVTT 0.8.6
Nextup: latest
Browser: Chrome
Dnd: 1.3.5

When starting a fight with multiple NPCs **while** NPCs **didn't** roll for initiative, the **first** automatically opened character sheet get stuck as soon as I roll for initiative (NPC group roll). I can't close the sheet, and it won't close automatically per settings.

https://user-images.githubusercontent.com/1687854/123014052-b2665100-d3c5-11eb-9a36-0ae9a0f8c2d8.mp4

I also get this error when attempting to close the sheet
![image](https://user-images.githubusercontent.com/1687854/123014795-471d7e80-d3c7-11eb-8eb0-4a6e818b9eb0.png)

**Comment by DarKDinDoN** [comment]
Module config if any help
![image](https://user-images.githubusercontent.com/1687854/123235920-9dc8ac80-d4dc-11eb-94a7-8c56cfe2c63c.png)

**Comment by kandashi** [comment]
I cannot reproduce this, but i'm in 0.8.8.

**Comment by DarKDinDoN** [comment]
@kandashi me neither on 0.8.8!
