### ISSUE TITLE
[BUG] Multiple errors in the console

### ISSUE THREAD

**Issue by DarKDinDoN** [kandashi/Next-Up#104]
Hello,

FVTT 0.8.6
Nextup: latest
Browser: Chrome
Dnd: 1.3.5

Here are the errors I experience in the console.

Adding tokens to the combat tracker (no initiative roll yet)
![image](https://user-images.githubusercontent.com/1687854/123014554-cc546380-d3c6-11eb-919f-3dc14c10e6a7.png)

Rolling initiative for NPCs (not always tho)
![image](https://user-images.githubusercontent.com/1687854/123014603-e5f5ab00-d3c6-11eb-99c4-ea968f852abc.png)

**Comment by kandashi** [comment]
So the first errors are if the path for the marker is not a valid URL. please use the file picker to re-choose the asset.
The second error dosnt seem to be to do with Next Up at all

**Comment by DarKDinDoN** [comment]
@kandashi Well only turn marker was used at the time. Yes I don't use next up to track the turn. Checkbox for that option was disabled at the time ("Add turn marker")

**Comment by kandashi** [comment]
Id you set an image the error will go away, that's all I can say

**Comment by DarKDinDoN** [comment]
This is the configuration I used all along: 

![image](https://user-images.githubusercontent.com/1687854/123232014-07df5280-d4d9-11eb-9033-fb1016b4a4ba.png)

(pas to combattant doesn't seem to be working by the way)

**Comment by kandashi** [comment]
you have turned off "Enable Panning for Individual Clients"

**Comment by kandashi** [comment]
the silent error message will be removed in the next release
