### ISSUE TITLE
Allow for sheets to be closed after combat

### ISSUE THREAD

**Issue by tagnullde** [kandashi/Next-Up#107]
![image](https://user-images.githubusercontent.com/44159008/124311724-76be4a80-db6e-11eb-9ecf-a4f6b86aaf53.png)
![image](https://user-images.githubusercontent.com/44159008/124311765-876ec080-db6e-11eb-920c-bebb0fbca2a7.png)

Within the settings it's configured that all sheets should be closed.

![image](https://user-images.githubusercontent.com/44159008/124311310-d36d3580-db6d-11eb-9262-854205c3104d.png)

However, after ending the combat - the sheet stays open (sheets close while going through the rounds).
Disabled all modules but tidy5e, tidyUI and Next-up while testing.
No visible errors in the console either.

**Comment by kandashi** [comment]
The reason this dosnt happen is because it isnt intended to happen 😛 
I'll change this to a feature request, though its not likely to be for a while

**Comment by tagnullde** [comment]
xD

I could have sworn that it was closed after ending the combat. (Maybe another module?!)
Oh well - thanks for considering it as a feature though.

**Comment by kandashi** [comment]
Adding in next release
