### ISSUE TITLE
[Bug] No sound/animation

### ISSUE THREAD

**Issue by brunocalado** [kandashi/Next-Up#108]
Everytime I switch to a new actor in the combat tracker I got an error.

 sound/animation are not working.

![image](https://user-images.githubusercontent.com/4999783/124947697-74cd0f00-dfe6-11eb-85dd-f8fdd7ff5b73.png)

fvtt 8.8
swade 19.5
chrome
win10

**Comment by kandashi** [comment]
so the way things work is that the image is loaded but invisible on every token in combat, then made visible on their turn. This means that the image was never added. A refresh *should* reset this

**Comment by kandashi** [comment]
fixes should go out in next release
