### ISSUE TITLE
Sound volume setting for all sounds from Next Up

### ISSUE THREAD

**Issue by apoapostolov** [kandashi/Next-Up#109]
My players were unaware they have to lower the volume of interface sounds and were complaining about the "ear r-word" from the Start of Turn gong sound. I would like to be able to lower its volume by default, not requiring people to lower the volumes to not be overwhelmed by it.

**Comment by kandashi** [comment]
That seems reasonable, though it would still need tuning by individuals. I'll scope for the next update

**Comment by kandashi** [comment]
adding in next update
