### ISSUE TITLE
Next Up Conflicts with Token HUD Wildcard 

### ISSUE THREAD

**Issue by revilowaldow** [kandashi/Next-Up#117]
**Describe the bug**
When Token HUD Wildcard (THW) is used to change the token image then BEFORE combat has been initated. Next Up throws an error. During Combat and after combat, strange behaviour with the token markers is observed.

**To Reproduce**
BEFORE COMBAT:
1. Set up an [actor with wildcard token images](https://foundryvtt.com/article/tokens/). 
2. Place two copies of the token on the map.
3. Try to change the token image with THW's UI.
4. You may need to do this for alternating tokens to see the error.
5. Observe the `Cannot read property 'NUMaker' of undefined` error.

DURING COMBAT:
1. Add both tokens to the combat tracker and roll initiative.
2. Note one of the tokens will already have a turn marker.
3. Click through the turn order a few times to observe the expected Net Up behaviour.
4. Change the token image for a token that is not currently on its turn and observe it gains a Turn marker.
5. Note that multiple tokens are now marked.
6. Further note that multiple tokens can have their starting locations marked as well.
7. Click through the turn order to see the behaviour.
8. Note that the speed of rotation also seems to be affected when multiple tokens have turns marked.

AFTER COMBAT:
1. End Combat
2. Change the token image and observe that it becomes marked again while outside of combat.
3. This is true for all tokens.

**Expected behavior**
Not to throw errors before combat has started.
Turn marker to mark only the currently active token.
Turn markers to not appear outside combat.
Turn markers to have the correct rotation speed.
Turn markers to not be affected by an unrelated module.

**Screenshots**
![image](https://user-images.githubusercontent.com/52298102/130236227-279ba864-d751-459a-9f62-0c40996d88e6.png)

https://user-images.githubusercontent.com/52298102/130237223-924d781d-f46a-475a-8bd2-d8218a8b141a.mp4

**Environment:**
 - OS: Windows 10 OS Version 2009 (Build 19043.1110), Server on Ubuntu 20.04 LTS
 - Browser Chrome 92.0.4515.159 (Official Build) (64-bit) (cohort: Stable)
 - Foundry Version 0.8.9
 - Module Version 0.1.08
 - All Modules Disabled: No
 - Module List if no: 
![image](https://user-images.githubusercontent.com/52298102/130237379-0220fead-7f41-4762-9904-d077c237a9bc.png)

**Additional context**
How to use Token HUD Wildcard's UI:
![image](https://user-images.githubusercontent.com/52298102/130237474-91014849-494d-47f3-8979-1f4b83c77fba.png)

**Comment by kandashi** [comment]
Thank you for the indepth report. I believe this lines up with other bugs ive heard about. I'll need to re-visit sometime soon. Probably this week

**Comment by kandashi** [comment]
Fixed in #118

**Comment by revilowaldow** [comment]
Had a look at the commit, does this also fix the issues with changing the image during combat?

**Comment by kandashi** [comment]
Yes, any image change should be fine now

**Comment by revilowaldow** [comment]
Note that this didn't fix the various issues. 
If you follow the reproduction steps then all the issues described are still present except the thrown error in the first screenshot.

**Comment by crcoughenour** [comment]
Agreed, there are still some bugs. A key point is that in testing you'll want two connections open, such as a gm and a player:

- Switching token image while it is not your turn temporarily duplicates turn markers (as if it is your turn and the other token's turn). 
- Issues, including the above, resolve themselves for the client that switched the token after advancing the turn tracker but not for other clients. For the other clients they will see a static (non-rotating) turn marker for all unchanged token images. When it is a changed image's turn, the other clients will not see a turn marker at all.
