### ISSUE TITLE
[FEATURE] Auto Open Character Sheets for Players

### ISSUE THREAD

**Issue by Baxmann** [kandashi/Next-Up#125]
I don't know if this is a bug or it's a feature only for the DM, but I'd like Auto Open Character Sheets for Players.

Most of my players play in person, and we put Foundry up on a big TV. It'd be useful to have AOCS for them. I also have 1 player who lives too far away, and so having AOCS for him wouldn't be useful. 

Can you have a **_Per User Option_** to have Auto Open Character Sheet for Players?

**Comment by kandashi** [comment]
Closed in v0.1.13
