### ISSUE TITLE
Please consider bundling and minifying the JavaScript code

### ISSUE THREAD

**Issue by ghost91-** [kandashi/Next-Up#126]
**Is your feature request related to a problem? Please describe.**
Having to load several JS files per module greatly increases load times.

**Describe the solution you'd like**
In releases of the module, the JavaScript code is bundled into a single file and minified.

**Describe alternatives you've considered**
The situation becomes better with HTTP/2 but that's not an option for everybody.

**Additional context**
This would require adding a proper build process using a bundler like webpack or rollup etc. If you would like help with that, feel free to contact me :)

**Comment by kandashi** [comment]
Im afraid I dont have the time to do anything that isnt keeping things running along im afraid. An im not going to accept any PR's that will prevent me from understanding how things are working or from updating things in the future
