### ISSUE TITLE
feature request/inquiry:

### ISSUE THREAD

**Issue by Norc** [kandashi/Next-Up#18]
Full disclosure, I haven't tried this module yet, but are there any plans to add a visual indicator to the active Token, somewhat similar to Turn Marker?

In addition to being semi abandoned, the turn marker approach is deeply flawed because it uses tiles unnecessarily. Having a pixi effect applied to the active Token would be ideal. For example, it is difficult to see exactly which goblin in a dense cluster is acting.

Thanks this looks like a great module!!

**Comment by kandashi** [comment]
I have *no* idea about pixi stuff, but if you can point me in a direction then I'll 100% take a look

**Comment by Norc** [comment]
Awesome, I don't either, but I'll see if I can get someone to subcontract
in The League.

I thought you had a "highlight effect" in active auras if something was in
range, or am I going crazy? That's the sort of thing I was thinking of. The
only game I run is low module right now so I'm way out of practice sadly.

**Comment by kandashi** [comment]
So the stuff in active auras was using the token magic macros alongside DAE. Not an inbuilt thing

**Comment by kandashi** [comment]
I have gotten a basic "turn marker" like effect working
