### ISSUE TITLE
Pan to Next Combatant Issues

### ISSUE THREAD

**Issue by otigon** [kandashi/Next-Up#20]
Next Up Version 0.0.36
Foundry 0.7.9
5E 1.2.4

Pan to Next Combatant is not working for the GM Client (When Only Pan to Next Combatant is checked). Tested in a fresh world with only Next Up Active.

If Pan to Next Combatant is checked, and Enable Panning for Player Client is checked, the pan works for the GM and Client.

If Pan to Next Combatant is checked, and Enable Panning for Player Client is UNchecked, the pan does not work fore the GM.

If Pan to Next Combatant is un-checked, and Enable Panning for Player Client is checked, the pan does not work for the GM but does work for the Client.

I could be out of sorts if this is the intended behavior

**Comment by jessev14** [comment]
If I understand you correctly, you want to enable pan for the GM user, but disable pan for the players?

**Comment by otigon** [comment]
Correct, but now that I think about it its really not a problem to have both checked and let the players decide if they want to activate it. For some reason I thought I remembered the prior release only required the Pan to Next Combatant checked for the GM to have the functionality

**Comment by kandashi** [comment]
Yes, there are now 2 options. "Enable panning for player client" is a world wide toggle to enable specific clients to turn on their own panning. 
Pan to next combatant is the individual toggle, the GM must enable this themself to turn on panning for themself

**Comment by DFreds** [comment]
I think the issue here is that the settings make it seem like the "Enable Panning for Player Clients" will have no effect on the GM, and that the GM can still enable it for themselves. At least, that's what confused me. I think a rename of the description of the setting could help

**Comment by kandashi** [comment]
Yeah, maybe re-name to "enable planning setting for clients" would be more accurate

**Comment by kandashi** [comment]
closed with #21
