### ISSUE TITLE
BUG: Image marker doesn't disappear after end combat. 

### ISSUE THREAD

**Issue by Jonwh25** [kandashi/Next-Up#28]
After combat the turn marker image doesn't go away.

![image](https://user-images.githubusercontent.com/60674327/106818221-d995cf00-662c-11eb-9d43-f52b87812e2e.png)

**Comment by kandashi** [comment]
the update to 0.0.43 should fix this issue

**Comment by Jonwh25** [comment]
Fixed. Thank you. Close this out.
