### ISSUE TITLE
Marker doesn't show up

### ISSUE THREAD

**Issue by DarKDinDoN** [kandashi/Next-Up#29]
Hello,

Turn marker doesn't show up on my game

![image](https://user-images.githubusercontent.com/1687854/106874389-cd198100-66d5-11eb-9497-d6c291abc328.png)
(Tidy settings activated + next up).

Also, how this feature compares to https://github.com/kckaiwei/TurnMarker-alt and why the duplicate? (real question here, no judgment)

**Comment by kandashi** [comment]
The turn marker was an addon feature requested here #18, and it was an interesting project (I also believe that this is more performant and less likely to cause race condition issues or "abandoned" markers) 

About the lack of marker, make sure the ratio is high enough to see behind circular tokens. Also check the console for error logs

**Comment by DarKDinDoN** [comment]
Yep ratio wasn't high enough.
Thx!
