### ISSUE TITLE
Turn/Start markers fail to load from core data directory

### ISSUE THREAD

**Issue by MachDelta** [kandashi/Next-Up#33]
The module doesn't seem to want to display Turn or Start Turn icons sourced from the Core directory path. Also, if the Turn marker icon is from the core directory then the Start Turn marker will fail as well (even if set to Shadow).

**Comment by kandashi** [comment]
this is a current issue im trying to work around

**Comment by tagnullde** [comment]
Not sure if related or it's own issue.

The turnmarkers are not visible with most tokens. The token seem to obscure the effect. If I shrink the token (via token-ratio setting) down the marker becomes visible again.

![image](https://user-images.githubusercontent.com/44159008/109415153-4b0c3780-79b7-11eb-9d76-4a13cfe8bde9.png)

![image](https://user-images.githubusercontent.com/44159008/109415122-1e582000-79b7-11eb-9009-6eacca23069f.png)

**Comment by kandashi** [comment]
Increase the Marker Ratio in the settings

**Comment by tagnullde** [comment]
m)

**Comment by kandashi** [comment]
closed in 0.8.5 release
