### ISSUE TITLE
Feature Request - More Hex-Friendly Modern/Sci-Fi Options

### ISSUE THREAD

**Issue by tjlanza** [kandashi/Next-Up#35]
There's a bit of visual dissonance from a square-oriented object (circles with four points, elements broken up into quarters, etc.) spinning around hex-shaped icons. The module includes some very nice round+hex shaped turn markers, but they're very fantasy flavored. I would love to see more options that are circular in nature (a pattern that repeats more than four times) but also more hi-tech.

**Comment by kandashi** [comment]
Any additions are very welcome, however I am not an artist. If you can source artwork with licencing I would be more than happy to add more options. That being said, you can freely choose any image in your data folder to use instead, you are not limited to the seleection provided
