### ISSUE TITLE
Start Turn Marker not Working Properly

### ISSUE THREAD

**Issue by tjlanza** [kandashi/Next-Up#37]
FVTT 0.7.9 with D&D5E 1.2.4 or SR5 0.7.9.
No modules other than Next Up 0.0.45; this behavior did not exist with the previous version.

With "Start Turn Marker" set to "Shadow", tokens disappear. Either hovering the mouse over the active token or advancing the combat makes the token image vanish. It still responds to other mouse events normally - bars showing on hover, the name showing if set to, etc.

A browser refresh does not restore the token, as long as the option is enabled. Switching to "Icon" or "None", then refreshing, brings the icon back.

In testing "Shadow", I discovered that "Icon" no longer appears to work - the starting token marker is not generated. The tokens do not disappear, though.

**Comment by kandashi** [comment]
Can replicate, fix incoming

**Comment by kandashi** [comment]
closed with #39
