### ISSUE TITLE
Tokens disappearing and 2x2 token mark isnt centered

### ISSUE THREAD

**Issue by MarceloCortezz** [kandashi/Next-Up#38]
After I updated Next Up today, I am having some issues:
1. The Marker isnt centered in tokens greater than 1 by 1
![next-up](https://user-images.githubusercontent.com/79060716/107888149-83a50f00-6ee9-11eb-9529-ef75e1f7ba07.png)
2. When using Shadow configuration all the tokens disappear, hav
ing to refresh it so they can appear back again.

**Comment by kandashi** [comment]
Can replicate, fix incoming

**Comment by kandashi** [comment]
closed with #39
