### ISSUE TITLE
Conflict with "Pop Out" module

### ISSUE THREAD

**Issue by thadrine** [kandashi/Next-Up#44]
Saw you update it today, it works for the first round of combat, but on the second round it breaks again. 
![Untitled](https://user-images.githubusercontent.com/63060887/108447023-27b1f180-722d-11eb-87eb-f6fbbeb8cd9e.jpg)

**Comment by kandashi** [comment]
This happens when you already have a popout window open, im looking for a way to fix this

**Comment by kandashi** [comment]
fixed in 0.1.08
