### ISSUE TITLE
Request: Turn Marker Infront of Token

### ISSUE THREAD

**Issue by MiracleKnows** [kandashi/Next-Up#48]
The turn marker was usually in the front of the token in the past, but after the recent update, the turn marker is now hidden behind the token. Sometimes, it works when the token is a default token, I just don't know how to actually trigger that. After some time, the default token seems to have the same issue. 

(Note: Had to increase the scale on the second token because it was directly behind it.)

![image](https://user-images.githubusercontent.com/53079915/110885756-8bff3700-833b-11eb-8def-308295bdbdb8.png) 
![image](https://user-images.githubusercontent.com/53079915/110886069-1b0c4f00-833c-11eb-92d5-9f92c178c759.png)
![image](https://user-images.githubusercontent.com/53079915/110885872-ba7d1200-833b-11eb-8ac1-409c65065bb0.png)

**Comment by kandashi** [comment]
Im not entirely sure I understand. The turn marker will always be behind the token its marking, if you have tokens that take up the entire square you will need to increase the ratio of the marker

**Comment by MiracleKnows** [comment]
Huh... I just tested it with the previous release, and yeah. It looks like the turn marker really _was supposed_ to be behind the token. I might've actually ran into a reverse bug, but I don't know how to replicate it... Or maybe my eyes were just playing tricks on me! Either way, I'd like to turn this into a feature request if you don't mind! I really love the aesthetics of having the turn marker in front of the token instead of the back, and it would be really nice if there was an option to toggle that instead.

**Comment by kandashi** [comment]
Yeah, i can add that :)
