### ISSUE TITLE
Tokens shrink in size when moving to them at the start of their turn

### ISSUE THREAD

**Issue by Tetraplasm** [kandashi/Next-Up#49]
I'm fairly sure this is an issue with Next-Up, but it could be foul play between two or more modules. I'm using the pan/select feature from CUB, not sure if that's the issue.

Settings for this module:
sheet position: top left
which actor sheets to open: only unlinked
which combatant sheets to close: previous combatant
Which actor sheet types to close: unlinked only
popout actor sheets: 
enable panning for individual clients: X
pan to next combatant: 
remove pin icon from character sheets:
add turn marker: X
(using the "madmage" turn marker)
animation speed: 5
turn marker ratio: 1.35
start turn marker: shadow
(using the Blackcross icon)
Start turn marker ratio: 1

Not sure if this is a user error or what

**Comment by kandashi** [comment]
No, this is a long term bug that I cant pin down, it should only happen once per token
