### ISSUE TITLE
[REQUEST] Per Actor Turn Markers

### ISSUE THREAD

**Issue by KonteiKeisei** [kandashi/Next-Up#52]
I have players that would like to have custom turn markers.

The ability to set a custom turn marker per actor, as well as have a default marker for any actor that is not specifically assigned a turn marker would be great!

**Comment by hmqgg** [comment]
#51 is an implementation of setting turn markers by actor's Flag which can be set via Active Effects.
`flags.Next-Up.markerImage` & `flags.Next-Up.markerRatio` controls the image (path) and image scale.
`flags.Next-Up.startMarkerImage` & `flags.Next-Up.startMarkerRatio` works as the same but is for Turn Start Markers.
