### ISSUE TITLE
Conflict with Monster Blocks

### ISSUE THREAD

**Issue by otigon** [kandashi/Next-Up#6]
Tested with only Next Up and Monster Blocks active

1. Monster Block NPC sheets do not close if the next combatant is also an NPC using Monster Block sheet.
    - This effect stacks, leaving Monster Block sheets open until a Combatant is focused that does not use the Monster Block sheet.
   
2. Error in console log when focused Combatant is using a Monster Block sheet
![image](https://user-images.githubusercontent.com/73318661/104983675-dbc42080-59d2-11eb-87a8-628de029bb1e.png)

**Comment by kandashi** [comment]
Do you happen to be using the forge service?

**Comment by otigon** [comment]
This was on local, However, I can replicate on the Forge

**Comment by WildBillLives** [comment]
I can confirm this issue: running all the latest versions of Foundry/5E/Next Up/Monster Blocks on The Forge I get this same exact issue, with the same error message in the console.

**Comment by kandashi** [comment]
Im updating my system/modules now so I'll see if I can figure the cause
