### ISSUE TITLE
Please add chat message about whose turn it is

### ISSUE THREAD

**Issue by mkahvi** [kandashi/Next-Up#61]
Turn Marker had the nice message about whose turn it is, showing the token and the player name clearly.

Does not need to be much more than "Token Name's turn" with maybe their token graphic. But preferably this would also include markers so custom CSS or similar can be used to tweak it, unlike the aforementioned module.

It should be as small as reasonable while functioning as visible delineation of whose turn it is, especially for scrolling back and seeing what happened before (and potentially catch cases of skipping turns for example [announcement of turn with no action messages]).

Basic chat message idea is essentially this:
```hbs
<div class='next-up' data-token-id="{{token._id}}" data-user-id="{{user.id}}">
   <div class='flexrow'>
       <img class='portrait' src='{{token.data.img}}' />
       <div class='text flexcol'>
           <h2><span class='name'>{{token.name}}</span>'s turn</h2>
           <p class='player'>{{user.name}}</p>
       </div>       
   </div>
</div>
````

**Comment by kandashi** [comment]
I'll leave this functionality to https://gitlab.com/mkah-fvtt/agnostic/turn-announcer/-/blob/master/turn-announcer.mjs 👍
