### ISSUE TITLE
Actor sheets do not open

### ISSUE THREAD

**Issue by gravagehulk** [kandashi/Next-Up#64]
I've been using your module for a while and everything has been good. Recently, I started using an M1 Macbook Pro to run the game as GM in Edge (M1 optimized) browser. 

No matter what settings I use, the character sheets do not automatically open when the respective combatant comes up in the turn order. This always worked in the client (which I am still running on my PC). Has something changed, or is it some kind of incompatibility with this browser on Mac?I was using edge on the PC, but I always ran the game out of the client in the past.

**Comment by kandashi** [comment]
I have no idea about compatability with different browsers, macs expecially. I would hazard a guess that edge dosnt support some of the newer JS stuff, but thats pure speculation. If you can see if you get any console errors when advancing through combat that might help narrow things down

**Comment by gravagehulk** [comment]
There are no errors in console. This doesn't appear to be a compatibility issue. I just tested this again on my PC. NONE of the browsers will auto-open the character sheets. I can see them opening in the Foundry client, but on a web browser tab (with an account with GM permissions) on the same computer, they do not open. This is the case for Edge, Firefox, and Chrome. It only seems to work in the main Foundry client.

All of the Nextup settings are on in the GM account used to test.

**Comment by kandashi** [comment]
Then im guessing its a system issue. Which I cant do anything about unfortunatly

**Comment by gravagehulk** [comment]
Are you kidding? This is not a system issue. I am an IT Professional with over 20 years of experience with hardware and software. I tested this on every computer I have in my house. That's 1 Mac laptop, 4 PC Laptops, and 1 PC Desktop. I tested it on all of the browsers. All of them are confirming the same behavior. As far as I can tell, it only opens the characters sheet in the Foundry client. It will not do it in the web browser. At all.

Did you even test it, or are you just blaming the user? Because I'm not your typical end user. 

Look, I appreciate the work you have done on this module and it is very important to my games, but I have worked with other developers on quite a few of the other mods and none of them were so quick to dismiss my concerns. I'd appreciate it if you'd at least take a look. I did extensive testing before I reported this.

**Comment by kandashi** [comment]
Sorry i misread, I though you said tested on all browsers on the same machine.

**Comment by kandashi** [comment]
All I'll say is that I develop on Win 10 using Chrome, not in the client at all. Without any error logs, or anything **at all** to go on, I'm really not sure what you want me to do here.

**Comment by gravagehulk** [comment]
No worries. I haven't been very good at updating the original issue. I've been testing it on my other machines since the original occurrence. In real time, I can see the character sheets opening on the Foundry client when I advance the initiative order, but they never open in the browser. This is true for Firefox, Chrome, and Edge on both Mac and PC. I'm not sure if running a dedicated server would be different, as I'm self-hosting using the client.

It seems like it ONLY opens the actor sheets in the Foundry client currently. I was hoping it was just a bug or that someone else may have reported it in the past. I used to run my games exclusively through the Foundry client, so I never noticed until I switched to a browser.

**Comment by gravagehulk** [comment]
So, have you tested in Chrome? Do the character sheets open when you advance the tracker? Is your Foundry instance running minimized, hosted, or running as a dedicated server? I'm just wondering if you can duplicate the issue.

**Comment by kandashi** [comment]
Testing in chrome now. Running the server in the app on the same machine. Everything works as intended

**Comment by gravagehulk** [comment]
That's odd. Testing on the same Windows 10 machine that's running the Foundry client in the most recent version of Chrome, the character sheets do not pop up for me in the browser. 

You aren't running an Alpha or Beta version of Foundry, are you? My versions are:

Foundry: 0.7.9
D&D: 1.2.4

**Comment by kandashi** [comment]
That's the same as mine yeah. Would you be happy PMing me and invite to your server through discord to see what's up locally?

**Comment by gravagehulk** [comment]
I could do that. How do I find you on discord? Am I sharing my screen with you, or are you actually wanting to connect as a user?

**Comment by gravagehulk** [comment]
Thanks again for your help. Single GM works fine. Closing.
