### ISSUE TITLE
Next Up Not Functioning On Second Encounter After Refresh

### ISSUE THREAD

**Issue by CMYKMatter** [kandashi/Next-Up#65]
**Problem:** 

Next Up only seems to trigger after the first time creating an encounter. It does not trigger on subsequent encounters.

**Steps to Reproduce:** 

1. Launch your world with Next Up enabled
2. Create a new encounter by highlighting combatants and toggling their combat state
3. Click Begin Combat
4. Click End Combat and select yes to clear the turn tracker 
5. Highlight the tokens again and toggle their combat state
6. Click Begin Combat

When following these steps, no turn marker shows, nor do the automatic sheet openings work.  Panning to targets doesn't work either.  The combat acts as if Next Up isn't even installed. When you refresh the page, Next Up functionality returns but this is less than ideal.

**Things I've Tried**

- Toggling Next Up off & on.  This restores functionality for the first fight but not the second
- Turn off all other modules other than Next Up. The problem persists
- Creating a new world where only Next Up is installed. The problem persists 

If you need me to record a video or something I would be happy to try.  I'm not sure why this is happening.  I'm on the latest version of DnD5e, Foundry, and Next Up. I'm accessing it through the newest version of Chrome on a DigitalOcean droplet install.  Let me know if you need more information .

Thanks for the great work on this mod!

**Comment by kandashi** [comment]
This should only happen if you have combats active on multiple scenes at once, and end one of them. 
Instead of just fixing this issue, im going to just re-write the module to clean up😁 

It'll be a few days in the making, but for now you can roll back to https://github.com/kandashi/Next-Up/releases/download/0.0.55/module.json
