### ISSUE TITLE
Going backwards in combat order leaves animations behind

### ISSUE THREAD

**Issue by Noshei** [kandashi/Next-Up#67]
If you go backwards in the initiative order, the animation will be left behind.  This can result on animations on multiple tokens at once, though this appears to cap at 5 animations at once.

![image](https://user-images.githubusercontent.com/8866000/116033230-48783800-a61e-11eb-8e37-582bce5871b9.png)

**Comment by Noshei** [comment]
Oh, and ending combat with the extra animations will leave them on the tokens.  The animations do get removed if you start combat again and cycle through each actor.

**Comment by kandashi** [comment]
*sigh*
