### ISSUE TITLE
Add option to scale markers less for bigger tokens and more for smaller

### ISSUE THREAD

**Issue by mkahvi** [kandashi/Next-Up#74]
1.5 ratio looks IMO great on 1 square sized tokens, but it's horrifyingly huge when the token is 4x4 sized (looks impressive tho).

I'd like something to ensure it shows up for tiny tiny less than cell sized tokens by being much larger than the token, and does not take immense space when on similarly gigantic tokens.

More explicitly, I'd like to be able to define the ratio to be 1.5 for 1 square sized things,  
Bound it to something like 2.0 for anything smaller, and cap it at ~1.1–1.3 for anything 3x3 sized or larger. And interpolate some value inbetween for all others..

**Comment by kandashi** [comment]
Maybe instead of a direct scale it could be changed to: how many grid squares does this extend past the tokens border

**Comment by mkahvi** [comment]
> Maybe instead of a direct scale it could be changed to: how many grid squares does this extend past the tokens border

I would find this acceptable compromise as the one I proposed would be annoying to implement in a nice way.
