### ISSUE TITLE
Support webm and add new pack

### ISSUE THREAD

**Issue by brunocalado** [kandashi/Next-Up#77]
Hi.

A friend <https://www.facebook.com/groups/379533023004717/user/100000544281866/> offered some of his work, but it's webm.

- [ ] Add support to webm
- [ ] Add the pack in the zip

Thank you for the great module.

**Comment by brunocalado** [comment]
https://user-images.githubusercontent.com/4999783/117983356-41834200-b30d-11eb-8e76-94ad4224b08e.mp4

**Comment by brunocalado** [comment]
Demo

**Comment by kandashi** [comment]
Before adding this to the module I need direct confirmation by the creator that I have their permission to use this. In the mean time you can just store this in your local directory and direct Next Up to that file

**Comment by brunocalado** [comment]
Webm is now working. How can I do it?

You can send him a message at facebook.

**Comment by kandashi** [comment]
Webm should work by default. Just select the file through the default file picker

**Comment by brunocalado** [comment]
I don't know what I'm doing wrong. I did that.

![image](https://user-images.githubusercontent.com/4999783/117985805-65e01e00-b30f-11eb-908c-82dd77b50226.png)

**Comment by cefasheli** [comment]
kandashi i'm a creator, you are authorized to use them less the cyberpunk cause it have a trademark

**Comment by kandashi** [comment]
> @kandashi i'm a creator, you are authorized to use them less the cyberpunk cause it have a trademark. Do you need more? 

All good, thanks 👍

**Comment by cefasheli** [comment]
@kandashi can you tell me the best settings for these videos? Do you want something especial? Do you like to suggest a theme?

**Comment by brunocalado** [comment]
I removed the cyberpunk one

[turnmaker.zip](https://github.com/kandashi/Next-Up/files/6468095/turnmaker.zip)

**Comment by kandashi** [comment]
closed by #79
