### ISSUE TITLE
Turn Marker not syncing properly between clients, sometimes also duplicating

### ISSUE THREAD

**Issue by dmaneyapanda** [kandashi/Next-Up#78]
Using 0.7.9, only Next Up enabled

1) Start a combat (with 3 tokens, should it matter).  Turn Marker appears under correct token in all clients.

Have one client End Turn (either the GM, or the player whose turn it was).  Turn Marker moves to next token as expected in that player's client:
![image](https://user-images.githubusercontent.com/2231877/118369409-37fa1400-b571-11eb-832f-3d7f5a6d932b.png)

However, in the other clients, the Turn Marker is still on the first token:
![image](https://user-images.githubusercontent.com/2231877/118369435-59f39680-b571-11eb-896c-25b71cbc861d.png)

Reloading the misbehaving client causes the turn marker to move to the currently currect active token, but as soon as the End Turn button is pressed again, it will only update correctly for that client, the rest will get out of sync immediately again.

2) Sometimes, and I'm not exactly sure what causes it (it may be just any time the GM is out of sync and then the GM ends a turn), the Turn Markers will start duplicating as well.
![image](https://user-images.githubusercontent.com/2231877/118369586-eaca7200-b571-11eb-96dd-62f0b9f90803.png)

**Comment by kandashi** [comment]
What version of Next Up is this on, 0.0.61 should be pretty stable about this

**Comment by dmaneyapanda** [comment]
0.0.59.  When I click the update button in foundry it tells me this is the most recent version.

**Comment by dmaneyapanda** [comment]
I uninstalled and reinstalled and now have 0.0.62.  Not sure what the issue was there.  Thanks!

**Comment by Th3Rom3** [comment]
Had the same issue as @dmaneyapanda and also did not receive the update from 0.0.59 via the normal update interface. Manually uninstalling and reinstalling seems to have fixed my problems. Thanks for the work on the module.

**Comment by kandashi** [comment]
Glad thats fixed, there was a little error in the 0.6 update
