### ISSUE TITLE
Popped out NPC/character blocking out screen upon taking damage

### ISSUE THREAD

**Issue by NateHawk85** [kandashi/Next-Up#81]
Versions: 
Next Up v0.0.62
D&D5e 1.2.4
Both Tidy5e Sheet and the Default 5e NPC Character Sheet

Current settings (that I believe affect this functionality):
Sheets to Open --> Only Unlinked
Sheets to Close --> Unlinked Only (not sure if unrelated, but this does not close popped-out sheets once the token's turn is over)
Sheets to Close --> Unlinked Only
Combatant Sheets to Close --> Previous Combatant
Popout Actor Sheets --> Enabled (this seems to be the setting that causes things to fail)

1) NPC takes turn in encounter, opens sheet as intended.
2) Next token's turn. If the NPC token takes damage while its character sheet is popped out, it causes a gray "character sheet-like" window to pop up alongside the already-popped out sheet. 
3) Closing the "gray" window OR the popped out window will "pop in" the NPC character sheet, except the sheet will take up the entirety of the screen and be unclosable, unmodifiable, and requires a refresh of the GM's browser window in order to do anything.

Before taking damage (next token's turn after NPC and NPC's sheet is popped out):
![image](https://user-images.githubusercontent.com/7596412/118580361-5caee100-b755-11eb-83e0-8a9f1621a73f.png)

After taking damage:
![image](https://user-images.githubusercontent.com/7596412/118580387-68020c80-b755-11eb-9e00-40b7898a07b1.png)

After closing the NPC's sheet that's popped out:
![image](https://user-images.githubusercontent.com/7596412/118580427-78b28280-b755-11eb-8ad3-103c8e86c816.png)

At this point, the GM must refresh the browser as that sheet takes up the whole screen and is unmodifiable.

**Comment by kandashi** [comment]
This should be fixed with popout v2
