### ISSUE TITLE
ReferenceError: currentSheet is not defined

### ISSUE THREAD

**Issue by Oshcakes** [kandashi/Next-Up#90]
After each turn this error is logged in the console, along with a lot of deprecated warnings. Not sure if this is causing any issues though.

![image](https://user-images.githubusercontent.com/61471647/120876250-530ae300-c575-11eb-848f-6fb189eff52c.png)

**Comment by Oshcakes** [comment]
By the way this happens with just these modules enabled (without the warnings above)
lib-wrapper--v1.6.2.0;
Next-Up--v0.1.01;
tidy-ui_game-settings--v0.1.23;

![image](https://user-images.githubusercontent.com/61471647/120893600-bd556f00-c5d9-11eb-950c-a65fb9be9933.png)

**Comment by Freeze021** [comment]
Error is caused by: 
```static async cycleSheets(currentToken, previousToken) {```

```if (combatFocusEnable) {
                let currentSheet = currentWindows.filter(i => i.token?.id === currentToken.id);
                let sheet;```

should be / could be:

```let currentSheet = currentWindows.filter(i => i.token?.id === currentToken.id);
let sheet;
if (combatFocusEnable) { etc... ```

**Comment by kandashi** [comment]
thanks for the find @Freeze021
