### ISSUE TITLE
Sheet displayed wrong at change of turn-Savage Worlds

### ISSUE THREAD

**Issue by flynnkd** [kandashi/Next-Up#91]
The popup sheet displayed at the start of a new turn is the first sheet of the last turn. SO is A was first this turn and B last, then in the new turn B was first it would still show A. Corrects after first character correctly. Savage Worlds with new cards every turn.

**Comment by flynnkd** [comment]
Still same issue above. Add in that it looks like it is stopping the reshuffle of the action deck so the table selection runs out (deck is expended).

**Comment by flynnkd** [comment]
PS I am using 8.6 and 19.3.

**Comment by flynnkd** [comment]
Turn marker is good now, but same issue first listed at start of turn applies.

**Comment by kandashi** [comment]
Im not sure ill be able to fix this, but ill take a look

**Comment by flynnkd** [comment]
Not sure if this will help you but Kobold Works - Ready Up seems to work correctly with the change of turn. ??  :)

**Comment by flynnkd** [comment]
Argh wrong button...
