### ISSUE TITLE
Removing combatant from combat tracker during his turn duplicates the animation.

### ISSUE THREAD

**Issue by devnagui** [kandashi/Next-Up#94]
![image](https://user-images.githubusercontent.com/19239974/121685086-6a872600-cab7-11eb-812b-90b2da44c01f.png)

Foundry: 0.8.6
Module: 
![image](https://user-images.githubusercontent.com/19239974/121693748-4fb9af00-cac1-11eb-9cbc-d67baa0a1d21.png)

Well, ping me if you need more info( Discord: Engrenado)

**Comment by kandashi** [comment]
Fixed in 0.1.04
