### ISSUE TITLE
Start Marker doesn't seem to work

### ISSUE THREAD

**Issue by Sekierer** [kandashi/Next-Up#95]
I downloaded Next-Up didn't change anything with folder structure or whatsoever. Selected different "turn marker" and "start marker" the incendiary one and the 'start' one for start and it gives me the following error. Incendiary current turn marker works, the start marker doesn't appear. 0.8.6 Foundry 1.3.3 5E and Next-Up freshly downloaded

![image](https://user-images.githubusercontent.com/64690637/121800832-5ae11c00-cc34-11eb-91ee-3ef42e8dfda5.png)

**Comment by Oshcakes** [comment]
I get the same issue hosted on the forge. Seems to remove the first 7 characters of the file path.
![image](https://user-images.githubusercontent.com/61471647/121827101-7d992200-cc80-11eb-9944-ec642347bbde.png)
 If I addd 7 characters to the start of the path it fixes it.
![image](https://user-images.githubusercontent.com/61471647/121827137-94d80f80-cc80-11eb-9306-4ebbbe217aa5.png)
 
Not sure whats going on here if that is the issue?
467               let startImage = token.actor.getFlag("Next-Up", "startMarkerImage") || NUStartImage.substring(7)

**Comment by Th3Rom3** [comment]
See also #88

**Comment by dirusulixes** [comment]
on fvtt 0.8.6 self-hosted I have the same error and the workaround suggested doesn't work. I always fails to load the asset.

**Comment by kandashi** [comment]
closeing as duplicate, will re-open #88
