### ISSUE TITLE
Start marker not centred on hexes

### ISSUE THREAD

**Issue by dirusulixes** [kandashi/Next-Up#97]
fvtt 0.8.6
Next-up 0.1.03

Minor cosmetic issue with the start marker that it's not centred on hexes. The turn marker is.
![Screenshot from 2021-06-15 13-55-44](https://user-images.githubusercontent.com/5693623/122056599-a5ec6200-cde1-11eb-8ea7-07a2527ccb02.png)

**Comment by kandashi** [comment]
Oh bugger :D
